name: gpn
channels:
  - conda-forge
  - pytorch
  # - nvidia # this is for NVIDIA GPU support (on cluster)
dependencies:
  - python=3.10

  # Core numerics / sci
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - h5py
  - pytables

  # Plotting / stats
  - matplotlib
  - seaborn
  - statsmodels
  - cycler

  # Images / CV
  - pillow
  - opencv

  # PyTorch (CPU/MPS on macOS)
  - pytorch
  - torchvision
  # - pytorch-cuda=12.4 # uncomment this line for GPU support (on cluster)

  # Jupyter kernel
  - ipykernel

  # pip for extra stuff
  - pip
  - pip:
      - timm
      - transformers
      - pysaliency